### PR TITLE
Dockerify this app

### PR DESCRIPTION
**Pull request by tuxnco**

### CODE REVIEW

**Review by tristan0x — CHANGES_REQUESTED** [review]
Shouldn't you add an `EXPOSE` directive to indicate that there is a service listening on port 3000?

**Comment by tristan0x** [comment]
I guess we need to upgrade the plan on quay.io :)

**Comment by tuxnco** [comment]
I think this can be public no ?
The fork is public, so... :-)

My 2 cents

**Comment by tuxnco** [comment]
No there is no need to specify the port exposed by the app inside the container (although the doc states to do so)
Firstly, that does not work, secondly that can be specified at runtime (see 1ff5de8)

**Comment by tristan0x** [comment]
`EXPOSE` directive works, it tells the `-P` option of `docker run` the list of ports that need to be allocated.

And yes, it is required if you want to to spawn several containers on the same server with ports allocated dynamically. And even if it is not used, it tells the user there is a service running and even provide him the port to reach it.

**Comment by tristan0x** [comment]
@tuxnco Yes, this can be public!

**Comment by tristan0x** [comment]
@tuxnco I wrote [this article](https://discuss.cogniteev.com/t/how-to-fork-open-source-projects/44) when @panthony asked for it few months ago. It is not absolute truth, but may provide you a guideline.

**Comment by tuxnco** [comment]
@tristan0x requested change was added.

**Pull request merged**
