### PR TITLE
make user agent configurable

### LINKED ISSUE #3: Make user agent configurable

### PR DESCRIPTION
**Pull request by tuxnco**
Now user agent can be overriden by environment variable USER_AGENT.

closes #3

### CODE REVIEW

**Comment by tristan0x** [comment]
IMHO we should keep the master branch oncrawl-agnostic to ease:
- the synchronization with the forked repository.
- the contributions we might want to do (like this PR for instance).

**Comment by tuxnco** [comment]
Ok, I'll work this out differently.

**Comment by tuxnco** [comment]
@tristan0x looks better to you now ?

**Review by tristan0x — COMMENTED** [review]
Maybe it is because I suck at JS, but I don't see where the `ua` variable is defined.

**Comment by tuxnco** [comment]
It's an argument to the (anonymous) function bro
Le mar. 27 sept. 2016 à 17:48, Tristan Carel notifications@github.com a
écrit :

**Comment by tristan0x** [comment]
LMTG

**Pull request merged**
